name: Deploy pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run pipeline-lint
      - name: Build
        run: npm run build

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
